
print("Data is here")


sensitive_information_data_1 = {
"aws-keys": r"([^A-Z0-9]|^)(AKIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{12,}",
 "sec": r"(aws_access|aws_secret|api[_-]?key|ListBucketResult|S3_ACCESS_KEY|Authorization:|RSA PRIVATE|Index of|aws_|secret|ssh-rsa AA)",
    "ip": r"(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])",
}

enum_data_I1 = {
"s3-buckets": [         r"[a-z0-9.-]+\\.s3\\.amazonaws\\.com",         r"[a-z0-9.-]+\\.s3-[a-z0-9-]\\.amazonaws\\.com",         r"[a-z0-9.-]+\\.s3-website[.-](eu|ap|us|ca|sa|cn)",         r"//s3\\.amazonaws\\.com/[a-z0-9._-]+",         r"//s3-[a-z0-9-]+\\.amazonaws\\.com/[a-z0-9._-]+"     ],
"servers": r"server: r",
"takeovers": [         r"There is no app configured at that hostname",         r"NoSuchBucket",         r"No Such Account",         r"You're Almost There",         r"a GitHub Pages site here",         r"There's nothing here",         r"project not found",         r"Your CNAME settings",         r"InvalidBucketName",         r"PermanentRedirect",         r"The specified bucket does not exist",         r"Repository not found",         r"Sorry, We Couldn't Find That Page",         r"The feed has not been found.",         r"The thing you were looking for is no longer here, or never was",         r"Please renew your subscription",         r"There isn't a Github Pages site here.",         r"We could not find what you're looking for.",         r"No settings were found for this company:",         r"No such app",         r"is not a registered InCloud YouTrack",         r"Unrecognized domain",         r"project not found",         r"This UserVoice subdomain is currently available!",         r"Do you want to register",         r"Help Center Closed"     ],

}

enum_data_I2 = {
    "base64": r"([^A-Za-z0-9+/]|^)(eyJ|YTo|Tzo|PD[89]|aHR0cHM6L|aHR0cDo|rO0)[%a-zA-Z0-9+/]+={0,2}",
    "cors": r"Access-Control-Allow",
    "debug-pages": r"(Application-Trace|Routing Error|DEBUG\"? ?[=:] ?True|Caused by:|stack trace:|Microsoft .NET Framework|Traceback|[0-9]:in `|#!/us|WebApplicationException|java\\.lang\\.|phpinfo|swaggerUi|on line [0-9]|SQLSTATE)",
    "firebase": r"firebaseio.com",
    "fw": [         r"django",         r"laravel",         r"symfony",         r"graphite",         r"grafana",         r"X-Drupal-Cache",         r"struts",         r"code ?igniter",         r"cake ?php",         r"grails",         r"elastic ?search",         r"kibana",         r"log ?stash",         r"tomcat",         r"jenkins",         r"hudson",         r"com.atlassian.jira",         r"Apache Subversion",         r"Chef Server",         r"RabbitMQ Management",         r"Mongo",         r"Travis CI - Enterprise",         r"BMC Remedy",         r"artifactory"     ],
    "go-functions": r"func [a-z0-9_]+\\(",
    "http-auth": r"[a-z0-9_/\\.:-]+@[a-z0-9-]+\\.[a-z0-9.-]+",
    "json-sec": r"(\\\\?\"|&quot;|%22)[a-z0-9_-]*(api[_-]?key|S3|aws_|secret|passw|auth)[a-z0-9_-]*(\\\\?\"|&quot;|%22): ?(\\\\?\"|&quot;|%22)[^\"&]+(\\\\?\"|&quot;|%22)",
    "meg-headers": r"^\u003c [a-z0-9_\\-]+: .*",
    "php-curl": r"CURLOPT_(HTTPHEADER|HEADER|COOKIE|RANGE|REFERER|USERAGENT|PROXYHEADER)",
    "php-errors": [         r"php warning",         r"php error",         r"fatal error",         r"uncaught exception",         r"include_path",         r"undefined index",         r"undefined variable",         r"\\?php",         r"<\\?[^x]",         r"stack trace\\:",         r"expects parameter [0-9]*",         r"Debug Trace"     ],
    "php-serialized": [         r"a:[0-9]+:{",         r"O:[0-9]+:\"",         r"s:[0-9]+:\""     ],
    "php-sinks": r"[^a-z0-9_](system|exec|popen|pcntl_exec|eval|create_function|unserialize|file_exists|md5_file|filemtime|filesize|assert) ?\\(",
    "php-sources": [         r"\\$_(POST|GET|COOKIE|REQUEST|SERVER|FILES)",         r"php://(input|stdin)"     ],
    "strings": [         r"\"[^\"]+\"",         "'[^']+'"     ],
    "upload-fields": r"\u003cinput[^\u003e]+type=[\"']?file[\"']?",
    "urls": r"https?://[^\"\\'> ]+",
}


for k, v in enum_data_I2.items():
  pass
  #print(v)


takeovers = {
"AWS/S3":
"The specified bucket does not exist",
"Bitbucket":
"Repository not found",
"Cloudfront":
"Bad Request: ERROR: The request could not be satisfied",
"Desk":
"Please try again or try Desk.com free for 14 days.",
"Fastly":
"Fastly error: unknown domain:",
"Feedpress":
"The feed has not been found.",
"Ghost":
"The thing you were looking for is no longer here, or never was",
"Github":
"There isn't a GitHub Pages site here",
"Help Juice":
"We could not find what you're looking for",
"Help Scout":
"No settings were found for this company",
"Heroku":
"No such app",
"JetBrains":
"is not a registered InCloud YouTrack",
"Mashery":
"Unrecognized domain",
"Readme.io":
"Project doesnt exist... yet!",
"Shopify":
"Sorry, this shop is currently unavailable",
"Surge.sh":
"project not found",
"Tumblr":
"Whatever you were looking for doesn't currently exist at this address",
"Tilda":
"Please renew your subscription",
"Unbounce":
"The requested URL was not found on this server",
"UserVoice":
"This UserVoice subdomain is currently available",
"Wordpress":
"Do you want to register ",
"Zendesk":
"Help Center Closed",
"Acquia":
"Web Site Not Found",
"Agile CRM":
"Sorry, this page is no longer available.",
"Airee.ru":
"Ошибка 402. Сервис",
"Anima":
"If this is your website and you've just created it, try refreshing in a minute",
"Campaign Monitor":
"Trying to access your account?",
"Digital Ocean":
"Domain uses DO name serves with no records in DO.",
"Gemfury":
"404: This page could not be found.",
"Google Cloud Storage":
"The specified bucket does not exist.",
"HatenaBlog":
"404 Blog is not found",
"Intercom":
"Uh oh. That page doesn't exist.",
"Kinsta":
"No Site For Domain",
"LaunchRock":
"It looks like you may have taken a wrong turn somewhere. Don't worry...it happens to all of us.",
"Ngrok":
"ngrok.io not found",
"Pantheon":
"404 error unknown site!",
"Pingdom":
"Sorry, couldn't find the status page",
"SmartJobBoard":
"This job board website is either expired or its domain name is invalid.",
"Smartling":
"Domain is not configured",
"Statuspage":
"Status page pushed a DNS verification in order to prevent malicious takeovers what they mentioned in",
"Strikingly":
"But if you're looking to build your own website, <br/>you've come to the right place.",
"Uberflip":
"Non-hub domain, The URL you've accessed does not provide a hub.",
"Webflow":
"The page you are looking for doesn't exist or has been moved.",
"Worksites":
"Hello! Sorry, but the website you&rsquo;re looking for doesn&rsquo;t exist.",
}

for k, v in takeovers.items():
  pass
  #print(v)


sensitive_information_data_2 = [
  {
    "part": "extension",
    "match": ".pem",
    "name": "Potential cryptographic private key"
  },
  {
    "part": "extension",
    "match": ".log",
    "name": "Log file"
  },
  {
    "part": "extension",
    "match": ".pkcs12",
    "name": "Potential cryptographic key bundle"
  },
  {
    "part": "extension",
    "match": ".p12",
    "name": "Potential cryptographic key bundle"
  },
  {
    "part": "extension",
    "match": ".pfx",
    "name": "Potential cryptographic key bundle"
  },
  {
    "part": "extension",
    "match": ".asc",
    "name": "Potential cryptographic key bundle"
  },
  {
    "part": "filename",
    "match": "otr.private_key",
    "name": "Pidgin OTR private key"
  },
  {
    "part": "extension",
    "match": ".ovpn",
    "name": "OpenVPN client configuration file"
  },
  {
    "part": "extension",
    "match": ".cscfg",
    "name": "Azure service configuration schema file"
  },
  {
    "part": "extension",
    "match": ".rdp",
    "name": "Remote Desktop connection file"
  },
  {
    "part": "extension",
    "match": ".mdf",
    "name": "Microsoft SQL database file"
  },
  {
    "part": "extension",
    "match": ".sdf",
    "name": "Microsoft SQL server compact database file"
  },
  {
    "part": "extension",
    "match": ".sqlite",
    "name": "SQLite database file"
  },
  {
    "part": "extension",
    "match": ".sqlite3",
    "name": "SQLite3 database file"
  },
  {
    "part": "extension",
    "match": ".bek",
    "name": "Microsoft BitLocker recovery key file"
  },
  {
    "part": "extension",
    "match": ".tpm",
    "name": "Microsoft BitLocker Trusted Platform Module password file"
  },
  {
    "part": "extension",
    "match": ".fve",
    "name": "Windows BitLocker full volume encrypted data file"
  },
  {
    "part": "extension",
    "match": ".jks",
    "name": "Java keystore file"
  },
  {
    "part": "extension",
    "match": ".psafe3",
    "name": "Password Safe database file"
  },
  {
    "part": "filename",
    "match": "secret_token.rb",
    "name": "Ruby On Rails secret token configuration file"
  },
  {
    "part": "filename",
    "match": "carrierwave.rb",
    "name": "Carrierwave configuration file"
  },
  {
    "part": "filename",
    "match": "database.yml",
    "name": "Potential Ruby On Rails database configuration file"
  },
  {
    "part": "filename",
    "match": "omniauth.rb",
    "name": "OmniAuth configuration file"
  },
  {
    "part": "filename",
    "match": "settings.py",
    "name": "Django configuration file"
  },
  {
    "part": "extension",
    "match": ".agilekeychain",
    "name": "1Password password manager database file"
  },
  {
    "part": "extension",
    "match": ".keychain",
    "name": "Apple Keychain database file"
  },
  {
    "part": "extension",
    "match": ".pcap",
    "name": "Network traffic capture file"
  },
  {
    "part": "extension",
    "match": ".gnucash",
    "name": "GnuCash database file"
  },
  {
    "part": "filename",
    "match": "jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml",
    "name": "Jenkins publish over SSH plugin file"
  },
  {
    "part": "filename",
    "match": "credentials.xml",
    "name": "Potential Jenkins credentials file"
  },
  {
    "part": "extension",
    "match": ".kwallet",
    "name": "KDE Wallet Manager database file"
  },
  {
    "part": "filename",
    "match": "LocalSettings.php",
    "name": "Potential MediaWiki configuration file"
  },
  {
    "part": "extension",
    "match": ".tblk",
    "name": "Tunnelblick VPN configuration file"
  },
  {
    "part": "filename",
    "match": "Favorites.plist",
    "name": "Sequel Pro MySQL database manager bookmark file"
  },
  {
    "part": "filename",
    "match": "configuration.user.xpl",
    "name": "Little Snitch firewall configuration file"
  },
  {
    "part": "extension",
    "match": ".dayone",
    "name": "Day One journal file"
  },
  {
    "part": "filename",
    "match": "journal.txt",
    "name": "Potential jrnl journal file"
  },
  {
    "part": "filename",
    "match": "knife.rb",
    "name": "Chef Knife configuration file"
  },
  {
    "part": "filename",
    "match": "proftpdpasswd",
    "name": "cPanel backup ProFTPd credentials file"
  },
  {
    "part": "filename",
    "match": "robomongo.json",
    "name": "Robomongo MongoDB manager configuration file"
  },
  {
    "part": "filename",
    "match": "filezilla.xml",
    "name": "FileZilla FTP configuration file"
  },
  {
    "part": "filename",
    "match": "recentservers.xml",
    "name": "FileZilla FTP recent servers file"
  },
  {
    "part": "filename",
    "match": "ventrilo_srv.ini",
    "name": "Ventrilo server configuration file"
  },
  {
    "part": "filename",
    "match": "terraform.tfvars",
    "name": "Terraform variable config file"
  },
  {
    "part": "filename",
    "match": ".exports",
    "name": "Shell configuration file"
  },
  {
    "part": "filename",
    "match": ".functions",
    "name": "Shell configuration file"
  },
  {
    "part": "filename",
    "match": ".extra",
    "name": "Shell configuration file"
  },
  {
    "part": "filename",
    "regex": r"^.*_rsa$",
    "name": "Private SSH key"
  },
  {
    "part": "filename",
    "regex": r"^.*_dsa$",
    "name": "Private SSH key"
  },
  {
    "part": "filename",
    "regex": r"^.*_ed25519$",
    "name": "Private SSH key"
  },
  {
    "part": "filename",
    "regex": r"^.*_ecdsa$",
    "name": "Private SSH key"
  },
  {
    "part": "path",
    "regex": r"\\.?ssh/config$",
    "name": "SSH configuration file"
  },
  {
    "part": "extension",
    "regex": r"^key(pair)?$",
    "name": "Potential cryptographic private key"
  },
  {
    "part": "filename",
    "regex": r"^\\.?(bash_|zsh_|sh_|z)?history$",
    "name": "Shell command history file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?mysql_history$",
    "name": "MySQL client command history file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?psql_history$",
    "name": "PostgreSQL client command history file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?pgpass$",
    "name": "PostgreSQL password file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?irb_history$",
    "name": "Ruby IRB console history file"
  },
  {
    "part": "path",
    "regex": r"\\.?purple/accounts\\.xml$",
    "name": "Pidgin chat client account configuration file"
  },
  {
    "part": "path",
    "regex": r"\\.?xchat2?/servlist_?\\.conf$",
    "name": "Hexchat/XChat IRC client server list configuration file"
  },
  {
    "part": "path",
    "regex": r"\\.?irssi/config$",
    "name": "Irssi IRC client configuration file"
  },
  {
    "part": "path",
    "regex": r"\\.?recon-ng/keys\\.db$",
    "name": "Recon-ng web reconnaissance framework API key database"
  },
  {
    "part": "filename",
    "regex": r"^\\.?dbeaver-data-sources.xml$",
    "name": "DBeaver SQL database manager configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?muttrc$",
    "name": "Mutt e-mail client configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?s3cfg$",
    "name": "S3cmd configuration file"
  },
  {
    "part": "path",
    "regex": r"\\.?aws/credentials$",
    "name": "AWS CLI credentials file"
  },
  {
    "part": "filename",
    "regex": r"^sftp-config(\\.json)?$",
    "name": "SFTP connection configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?trc$",
    "name": "T command-line Twitter client configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?(bash|zsh|csh)rc$",
    "name": "Shell configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?(bash_|zsh_)?profile$",
    "name": "Shell profile configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?(bash_|zsh_)?aliases$",
    "name": "Shell command alias configuration file"
  },
  {
    "part": "filename",
    "regex": r"config(\\.inc)?\\.php$",
    "name": "PHP configuration file"
  },
  {
    "part": "extension",
    "regex": r"^key(store|ring)$",
    "name": "GNOME Keyring database file"
  },
  {
    "part": "extension",
    "regex": r"^kdbx?$",
    "name": "KeePass password manager database file"
  },
  {
    "part": "extension",
    "regex": r"^sql(dump)?$",
    "name": "SQL dump file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?htpasswd$",
    "name": "Apache htpasswd file"
  },
  {
    "part": "filename",
    "regex": r"^(\\.|_)?netrc$",
    "name": "Configuration file for auto-login process"
  },
  {
    "part": "path",
    "regex": r"\\.?gem/credentials$",
    "name": "Rubygems credentials file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?tugboat$",
    "name": "Tugboat DigitalOcean management tool configuration"
  },
  {
    "part": "path",
    "regex": r"doctl/config.yaml$",
    "name": "DigitalOcean doctl command-line client configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?git-credentials$",
    "name": "git-credential-store helper credentials file"
  },
  {
    "part": "path",
    "regex": r"config/hub$",
    "name": "GitHub Hub command-line client configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?gitconfig$",
    "name": "Git configuration file"
  },
  {
    "part": "path",
    "regex": r"\\.?chef/(.*)\\.pem$",
    "name": "Chef private key"
  },
  {
    "part": "path",
    "regex": r"etc/shadow$",
    "name": "Potential Linux shadow file"
  },
  {
    "part": "path",
    "regex": r"etc/passwd$",
    "name": "Potential Linux passwd file",
    "comment": "Contains system user information"
  },
  {
    "part": "filename",
    "regex": r"^\\.?dockercfg$",
    "name": "Docker configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?npmrc$",
    "name": "NPM configuration file"
  },
  {
    "part": "filename",
    "regex": r"^\\.?env$",
    "name": "Environment configuration file"
  },
  {
    "part": "contents",
    "regex": r"(A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}",
    "name": "AWS Access Key ID Value"
  },
  {
    "part": "contents",
    "regex": r"((\\\"|'|`)?((?i)aws)?_?((?i)access)_?((?i)key)?_?((?i)id)?(\\\"|'|`)?(\\\\s{0,50})?(:|=>|=)(\\\\s{0,50})?(\\\"|'|`)?(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}(\\\"|'|`)?)",
    "regextype": "large",
    "name": "AWS Access Key ID"
  },
  {
    "part": "contents",
    "regex": r"((\\\"|'|`)?((?i)aws)?_?((?i)account)_?((?i)id)?(\\\"|'|`)?(\\\\s{0,50})?(:|=>|=)(\\\\s{0,50})?(\\\"|'|`)?[0-9]{4}-?[0-9]{4}-?[0-9]{4}(\\\"|'|`)?)",
    "regextype": "large",
    "name": "AWS Account ID"
  },
  {
    "part": "contents",
    "regex": r"((\\\"|'|`)?((?i)aws)?_?((?i)secret)_?((?i)access)?_?((?i)key)?_?((?i)id)?(\\\"|'|`)?(\\\\s{0,50})?(:|=>|=)(\\\\s{0,50})?(\\\"|'|`)?[A-Za-z0-9/+=]{40}(\\\"|'|`)?)",
    "regextype": "large",
    "name": "AWS Secret Access Key"
  },
  {
    "part": "contents",
    "regex": r"((\\\"|'|`)?((?i)aws)?_?((?i)session)?_?((?i)token)?(\\\"|'|`)?(\\\\s{0,50})?(:|=>|=)(\\\\s{0,50})?(\\\"|'|`)?[A-Za-z0-9/+=]{100,400}(\\\"|'|`)?)",
    "regextype": "large",
    "name": "AWS Session Token"
  },
  {
    "part": "contents",
    "regex": r"(?i)artifactory.{0,50}(\\\"|'|`)?[a-zA-Z0-9=]{112}(\\\"|'|`)?",
    "regextype": "large",
    "name": "Artifactory"
  },
  {
    "part": "contents",
    "regex": r"(?i)codeclima.{0,50}(\\\"|'|`)?[0-9a-f]{64}(\\\"|'|`)?",
    "regextype": "large",
    "name": "CodeClimate"
  },
  {
    "part": "contents",
    "regex": r"EAACEdEose0cBA[0-9A-Za-z]+",
    "name": "Facebook access token"
  },
  {
    "part": "contents",
    "regex": r"((\\\"|'|`)?type(\\\"|'|`)?\\\\s{0,50}(:|=>|=)\\\\s{0,50}(\\\"|'|`)?service_account(\\\"|'|`)?,?)",
    "regextype": "large",
    "name": "Google (GCM) Service account"
  },
  {
    "part": "contents",
    "regex": r"(?:r|s)k_(live|test)_[0-9a-zA-Z]{24}",
    "name": "Stripe API key"
  },
  {
    "part": "contents",
    "regex": r"[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com",
    "name": "Google OAuth Key"
  },
  {
    "part": "contents",
    "regex": r"AIza[0-9A-Za-z\\\\-_]{35}",
    "name": "Google Cloud API Key"
  },
  {
    "part": "contents",
    "regex": r"ya29\\\\.[0-9A-Za-z\\\\-_]+",
    "name": "Google OAuth Access Token"
  },
  {
    "part": "contents",
    "regex": r"sk_[live|test]_[0-9a-z]{32}",
    "name": "Picatic API key"
  },
  {
    "part": "contents",
    "regex": r"sq0atp-[0-9A-Za-z\\-_]{22}",
    "name": "Square Access Token"
  },
  {
    "part": "contents",
    "regex": r"sq0csp-[0-9A-Za-z\\-_]{43}",
    "name": "Square OAuth Secret"
  },
  {
    "part": "contents",
    "regex": r"access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}",
    "name": "PayPal/Braintree Access Token"
  },
  {
    "part": "contents",
    "regex": r"amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
    "name": "Amazon MWS Auth Token"
  },
  {
    "part": "contents",
    "regex": r"SK[0-9a-fA-F]{32}",
    "name": "Twilo API Key"
  },
  {
    "part": "contents",
    "regex": r"SG\\.[0-9A-Za-z\\-_]{22}\\.[0-9A-Za-z\\-_]{43}",
    "name": "SendGrid API Key"
  },
  {
    "part": "contents",
    "regex": r"key-[0-9a-zA-Z]{32}",
    "name": "MailGun API Key"
  },
  {
    "part": "contents",
    "regex": r"[0-9a-f]{32}-us[0-9]{12}",
    "name": "MailChimp API Key"
  },
  {
    "part": "contents",
    "regex": r"sshpass -p.*['|\\\"]",
    "regextype": "large",
    "name": "SSH Password"
  },
  {
    "part": "contents",
    "regex": r"(https\\\\://outlook\\\\.office.com/webhook/[0-9a-f-]{36}\\\\@)",
    "name": "Outlook team"
  },
  {
    "part": "contents",
    "regex": r"(?i)sauce.{0,50}(\\\"|'|`)?[0-9a-f-]{36}(\\\"|'|`)?",
    "name": "Sauce Token"
  },
  {
    "part": "contents",
    "regex": r"(xox[pboa]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})",
    "name": "Slack Token"
  },
  {
    "part": "contents",
    "regex": r"https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}",
    "name": "Slack Webhook"
  },
  {
    "part": "contents",
    "regex": r"(?i)sonar.{0,50}(\\\"|'|`)?[0-9a-f]{40}(\\\"|'|`)?",
    "name": "SonarQube Docs API Key"
  },
  {
    "part": "contents",
    "regex": r"(?i)hockey.{0,50}(\\\"|'|`)?[0-9a-f]{32}(\\\"|'|`)?",
    "name": "HockeyApp"
  },
  {
    "part": "contents",
    "regex": r"([\\w+]{1,24})(://)([^$<]{1})([^\\s\";]{1,}):([^$<]{1})([^\\s\";/]{1,})@[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,24}([^\\s]+)",
    "regextype": "large",
    "name": "Username and password in URI"
  },
  {
    "part": "contents",
    "regex": r"oy2[a-z0-9]{43}",
    "name": "NuGet API Key"
  },
  {
    "part": "contents",
    "regex": r"hawk\\.[0-9A-Za-z\\-_]{20}\\.[0-9A-Za-z\\-_]{20}",
    "regextype": "large",
    "name": "StackHawk API Key"
  },
  {
    "part": "extension",
    "match": ".ppk",
    "name": "Potential PuTTYgen private key"
  },
  {
    "part": "filename",
    "match": "heroku.json",
    "name": "Heroku config file"
  },
  {
    "part": "extension",
    "match": ".sqldump",
    "name": "SQL Data dump file"
  },
  {
    "part": "filename",
    "match": "dump.sql",
    "name": "MySQL dump w/ bcrypt hashes"
  },
  {
    "part": "filename",
    "match": "id_rsa_pub",
    "name": "Public ssh key"
  },
  {
    "part": "filename",
    "match": "mongoid.yml",
    "name": "Mongoid config file"
  },
  {
    "part": "filename",
    "match": "salesforce.js",
    "name": "Salesforce credentials in a nodejs project"
  },
  {
    "part": "extension",
    "match": ".netrc",
    "name": "netrc with SMTP credentials"
  },
  {
    "part": "filename",
    "regex": r".remote-sync.json$",
    "name": "Created by remote-sync for Atom, contains FTP and/or SCP/SFTP/SSH server details and credentials"
  },
  {
    "part": "filename",
    "regex": r".esmtprc$",
    "name": "esmtp configuration"
  },
  {
    "part": "filename",
    "regex": r"^deployment-config.json?$",
    "name": "Created by sftp-deployment for Atom, contains server details and credentials"
  },
  {
    "part": "filename",
    "regex": r".ftpconfig$",
    "name": "Created by sftp-deployment for Atom, contains server details and credentials"
  },
  {
    "part": "contents",
    "regex": r"-----BEGIN (EC|RSA|DSA|OPENSSH|PGP) PRIVATE KEY",
    "name": "Contains a private key"
  },
  {
    "part": "contents",
    "regex": r"define(.{0,20})?(DB_CHARSET|NONCE_SALT|LOGGED_IN_SALT|AUTH_SALT|NONCE_KEY|DB_HOST|DB_PASSWORD|AUTH_KEY|SECURE_AUTH_KEY|LOGGED_IN_KEY|DB_NAME|DB_USER)(.{0,20})?['|\"].{10,120}['|\"]",
    "regextype": "large",
    "name": "WP-Config"
  },
  {
    "part": "contents",
    "regex": r"(?i)(aws_access_key_id|aws_secret_access_key)(.{0,20})?=.[0-9a-zA-Z\\/+]{20,40}",
    "name": "AWS cred file info"
  },
  {
    "part": "contents",
    "regex": r"(?i)(facebook|fb)(.{0,20})?(?-i)['\\\"][0-9a-f]{32}['\\\"]",
    "name": "Facebook Secret Key"
  },
  {
    "part": "contents",
    "regex": r"(?i)(facebook|fb)(.{0,20})?['\\\"][0-9]{13,17}['\\\"]",
    "name": "Facebook Client ID"
  },
  {
    "part": "contents",
    "regex": r"(?i)twitter(.{0,20})?['\\\"][0-9a-z]{35,44}['\\\"]",
    "name": "Twitter Secret Key"
  },
  {
    "part": "contents",
    "regex": r"(?i)twitter(.{0,20})?['\\\"][0-9a-z]{18,25}['\\\"]",
    "name": "Twitter Client ID"
  },
  {
    "part": "contents",
    "regex": r"(?i)github(.{0,20})?(?-i)['\\\"][0-9a-zA-Z]{35,40}['\\\"]",
    "name": "Github Key"
  },
  {
    "part": "contents",
    "regex": r"(?i)heroku(.{0,20})?['\"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['\"]",
    "name": "Heroku API key"
  },
  {
    "part": "contents",
    "regex": r"(?i)linkedin(.{0,20})?(?-i)['\\\"][0-9a-z]{12}['\\\"]",
    "name": "Linkedin Client ID"
  },
  {
    "part": "contents",
    "regex": r"(?i)linkedin(.{0,20})?['\\\"][0-9a-z]{16}['\\\"]",
    "name": "LinkedIn Secret Key"
  },
  {
    "part": "path",
    "regex": r"\\.?idea[\\\\\\/]WebServers.xml$",
    "name": "Created by Jetbrains IDEs, contains webserver credentials with encoded passwords (not encrypted!)"
  },
  {
    "part": "path",
    "regex": r"\\.?vscode[\\\\\\/]sftp.json$",
    "name": "Created by vscode-sftp for VSCode, contains SFTP/SSH server details and credentials"
  },
  {
    "part": "path",
    "regex": r"web[\\\\\\/]ruby[\\\\\\/]secrets.yml",
    "name": "Ruby on rails secrets.yml file (contains passwords)"
  },
  {
    "part": "path",
    "regex": r"\\.?docker[\\\\\\/]config.json$",
    "name": "Docker registry authentication file"
  },
  {
    "part": "path",
    "regex": r"ruby[\\\\\\/]config[\\\\\\/]master.key$",
    "name": "Rails master key (used for decrypting credentials.yml.enc for Rails 5.2+)"
  },
  {
    "part": "path",
    "regex": r"\\.?mozilla[\\\\\\/]firefox[\\\\\\/]logins.json$",
    "name": "Firefox saved password collection (can be decrypted using keys4.db)"
  },
  {
    "part": "filename",
    "match": "wallet.dat",
    "name": "Bitcoin Core wallet"
  },
  {
    "part": "filename",
    "match": "onion_v3_private_key",
    "name": "Private key for Bitcoin Core onion service"
  },
  {
    "part": "filename",
    "match": "bitcoin.conf",
    "name": "Bitcoin Core config"
  }
]

for element in sensitive_information_data_2:
    try:
        pass
        #print(element['regex'])
        #print(element['name'])
    except:
        continue


stopwords= [
    "client",
    "endpoint",
    "vpn",
    "_ec2_",
    "aws_",
    "authorize",
    "author",
    "define",
    "config",
    "credential",
    "setting",
    "sample",
    "xxxxxx",
    "000000",
    "buffer",
    "delete",
    "aaaaaa",
    "fewfwef",
    "getenv",
    "env_",
    "system",
    "example",
    "ecdsa",
    "sha256",
    "sha1",
    "sha2",
    "md5",
    "alert",
    "wizard",
    "target",
    "onboard",
    "welcome",
    "page",
    "exploit",
    "experiment",
    "expire",
    "rabbitmq",
    "scraper",
    "widget",
    "music",
    "dns_",
    "dns-",
    "yahoo",
    "want",
    "json",
    "action",
    "script",
    "fix_",
    "fix-",
    "develop",
    "compas",
    "stripe",
    "service",
    "master",
    "metric",
    "tech",
    "gitignore",
    "rich",
    "open",
    "stack",
    "irc_",
    "irc-",
    "sublime",
    "kohana",
    "has_",
    "has-",
    "fabric",
    "wordpres",
    "role",
    "osx_",
    "osx-",
    "boost",
    "addres",
    "queue",
    "working",
    "sandbox",
    "internet",
    "print",
    "vision",
    "tracking",
    "being",
    "generator",
    "traffic",
    "world",
    "pull",
    "rust",
    "watcher",
    "small",
    "auth",
    "full",
    "hash",
    "more",
    "install",
    "auto",
    "complete",
    "learn",
    "paper",
    "installer",
    "research",
    "acces",
    "last",
    "binding",
    "spine",
    "into",
    "chat",
    "algorithm",
    "resource",
    "uploader",
    "video",
    "maker",
    "next",
    "proc",
    "lock",
    "robot",
    "snake",
    "patch",
    "matrix",
    "drill",
    "terminal",
    "term",
    "stuff",
    "genetic",
    "generic",
    "identity",
    "audit",
    "pattern",
    "audio",
    "web_",
    "web-",
    "crud",
    "problem",
    "statu",
    "cms-",
    "cms_",
    "arch",
    "coffee",
    "workflow",
    "changelog",
    "another",
    "uiview",
    "content",
    "kitchen",
    "gnu_",
    "gnu-",
    "gnu.",
    "conf",
    "couchdb",
    "client",
    "opencv",
    "rendering",
    "update",
    "concept",
    "varnish",
    "gui_",
    "gui-",
    "gui.",
    "version",
    "shared",
    "extra",
    "product",
    "still",
    "not_",
    "not-",
    "not.",
    "drop",
    "ring",
    "png_",
    "png-",
    "png.",
    "actively",
    "import",
    "output",
    "backup",
    "start",
    "embedded",
    "registry",
    "pool",
    "semantic",
    "instagram",
    "bash",
    "system",
    "ninja",
    "drupal",
    "jquery",
    "polyfill",
    "physic",
    "league",
    "guide",
    "pack",
    "synopsi",
    "sketch",
    "injection",
    "svg_",
    "svg-",
    "svg.",
    "friendly",
    "wave",
    "convert",
    "manage",
    "camera",
    "link",
    "slide",
    "timer",
    "wrapper",
    "gallery",
    "url_",
    "url-",
    "url.",
    "todomvc",
    "requirej",
    "party",
    "http",
    "payment",
    "async",
    "library",
    "home",
    "coco",
    "gaia",
    "display",
    "universal",
    "func",
    "metadata",
    "hipchat",
    "under",
    "room",
    "config",
    "personal",
    "realtime",
    "resume",
    "database",
    "testing",
    "tiny",
    "basic",
    "forum",
    "meetup",
    "yet_",
    "yet-",
    "yet.",
    "cento",
    "dead",
    "fluentd",
    "editor",
    "utilitie",
    "run_",
    "run-",
    "run.",
    "box_",
    "box-",
    "box.",
    "bot_",
    "bot-",
    "bot.",
    "making",
    "sample",
    "group",
    "monitor",
    "ajax",
    "parallel",
    "cassandra",
    "ultimate",
    "site",
    "get_",
    "get-",
    "get.",
    "gen_",
    "gen-",
    "gen.",
    "gem_",
    "gem-",
    "gem.",
    "extended",
    "image",
    "knife",
    "asset",
    "nested",
    "zero",
    "plugin",
    "bracket",
    "mule",
    "mozilla",
    "number",
    "act_",
    "act-",
    "act.",
    "map_",
    "map-",
    "map.",
    "micro",
    "debug",
    "openshift",
    "chart",
    "expres",
    "backend",
    "task",
    "source",
    "translate",
    "jbos",
    "composer",
    "sqlite",
    "profile",
    "mustache",
    "mqtt",
    "yeoman",
    "have",
    "builder",
    "smart",
    "like",
    "oauth",
    "school",
    "guideline",
    "captcha",
    "filter",
    "bitcoin",
    "bridge",
    "color",
    "toolbox",
    "discovery",
    "new_",
    "new-",
    "new.",
    "dashboard",
    "when",
    "setting",
    "level",
    "post",
    "standard",
    "port",
    "platform",
    "yui_",
    "yui-",
    "yui.",
    "grunt",
    "animation",
    "haskell",
    "icon",
    "latex",
    "cheat",
    "lua_",
    "lua-",
    "lua.",
    "gulp",
    "case",
    "author",
    "without",
    "simulator",
    "wifi",
    "directory",
    "lisp",
    "list",
    "flat",
    "adventure",
    "story",
    "storm",
    "gpu_",
    "gpu-",
    "gpu.",
    "store",
    "caching",
    "attention",
    "solr",
    "logger",
    "demo",
    "shortener",
    "hadoop",
    "finder",
    "phone",
    "pipeline",
    "range",
    "textmate",
    "showcase",
    "app_",
    "app-",
    "app.",
    "idiomatic",
    "edit",
    "our_",
    "our-",
    "our.",
    "out_",
    "out-",
    "out.",
    "sentiment",
    "linked",
    "why_",
    "why-",
    "why.",
    "local",
    "cube",
    "gmail",
    "job_",
    "job-",
    "job.",
    "rpc_",
    "rpc-",
    "rpc.",
    "contest",
    "tcp_",
    "tcp-",
    "tcp.",
    "usage",
    "buildout",
    "weather",
    "transfer",
    "automated",
    "sphinx",
    "issue",
    "sas_",
    "sas-",
    "sas.",
    "parallax",
    "jasmine",
    "addon",
    "machine",
    "solution",
    "dsl_",
    "dsl-",
    "dsl.",
    "episode",
    "menu",
    "theme",
    "best",
    "adapter",
    "debugger",
    "chrome",
    "tutorial",
    "life",
    "step",
    "people",
    "joomla",
    "paypal",
    "developer",
    "solver",
    "team",
    "current",
    "love",
    "visual",
    "date",
    "data",
    "canva",
    "container",
    "future",
    "xml_",
    "xml-",
    "xml.",
    "twig",
    "nagio",
    "spatial",
    "original",
    "sync",
    "archived",
    "refinery",
    "science",
    "mapping",
    "gitlab",
    "play",
    "ext_",
    "ext-",
    "ext.",
    "session",
    "impact",
    "set_",
    "set-",
    "set.",
    "see_",
    "see-",
    "see.",
    "migration",
    "commit",
    "community",
    "shopify",
    "what'",
    "cucumber",
    "statamic",
    "mysql",
    "location",
    "tower",
    "line",
    "code",
    "amqp",
    "hello",
    "send",
    "index",
    "high",
    "notebook",
    "alloy",
    "python",
    "field",
    "document",
    "soap",
    "edition",
    "email",
    "php_",
    "php-",
    "php.",
    "command",
    "transport",
    "official",
    "upload",
    "study",
    "secure",
    "angularj",
    "akka",
    "scalable",
    "package",
    "request",
    "con_",
    "con-",
    "con.",
    "flexible",
    "security",
    "comment",
    "module",
    "flask",
    "graph",
    "flash",
    "apache",
    "change",
    "window",
    "space",
    "lambda",
    "sheet",
    "bookmark",
    "carousel",
    "friend",
    "objective",
    "jekyll",
    "bootstrap",
    "first",
    "article",
    "gwt_",
    "gwt-",
    "gwt.",
    "classic",
    "media",
    "websocket",
    "touch",
    "desktop",
    "real",
    "read",
    "recorder",
    "moved",
    "storage",
    "validator",
    "add-on",
    "pusher",
    "scs_",
    "scs-",
    "scs.",
    "inline",
    "asp_",
    "asp-",
    "asp.",
    "timeline",
    "base",
    "encoding",
    "ffmpeg",
    "kindle",
    "tinymce",
    "pretty",
    "jpa_",
    "jpa-",
    "jpa.",
    "used",
    "user",
    "required",
    "webhook",
    "download",
    "resque",
    "espresso",
    "cloud",
    "mongo",
    "benchmark",
    "pure",
    "cakephp",
    "modx",
    "mode",
    "reactive",
    "fuel",
    "written",
    "flickr",
    "mail",
    "brunch",
    "meteor",
    "dynamic",
    "neo_",
    "neo-",
    "neo.",
    "new_",
    "new-",
    "new.",
    "net_",
    "net-",
    "net.",
    "typo",
    "type",
    "keyboard",
    "erlang",
    "adobe",
    "logging",
    "ckeditor",
    "message",
    "iso_",
    "iso-",
    "iso.",
    "hook",
    "ldap",
    "folder",
    "reference",
    "railscast",
    "www_",
    "www-",
    "www.",
    "tracker",
    "azure",
    "fork",
    "form",
    "digital",
    "exporter",
    "skin",
    "string",
    "template",
    "designer",
    "gollum",
    "fluent",
    "entity",
    "language",
    "alfred",
    "summary",
    "wiki",
    "kernel",
    "calendar",
    "plupload",
    "symfony",
    "foundry",
    "remote",
    "talk",
    "search",
    "dev_",
    "dev-",
    "dev.",
    "del_",
    "del-",
    "del.",
    "token",
    "idea",
    "sencha",
    "selector",
    "interface",
    "create",
    "fun_",
    "fun-",
    "fun.",
    "groovy",
    "query",
    "grail",
    "red_",
    "red-",
    "red.",
    "laravel",
    "monkey",
    "slack",
    "supported",
    "instant",
    "value",
    "center",
    "latest",
    "work",
    "but_",
    "but-",
    "but.",
    "bug_",
    "bug-",
    "bug.",
    "virtual",
    "tweet",
    "statsd",
    "studio",
    "path",
    "real-time",
    "frontend",
    "notifier",
    "coding",
    "tool",
    "firmware",
    "flow",
    "random",
    "mediawiki",
    "bosh",
    "been",
    "beer",
    "lightbox",
    "theory",
    "origin",
    "redmine",
    "hub_",
    "hub-",
    "hub.",
    "require",
    "pro_",
    "pro-",
    "pro.",
    "ant_",
    "ant-",
    "ant.",
    "any_",
    "any-",
    "any.",
    "recipe",
    "closure",
    "mapper",
    "event",
    "todo",
    "model",
    "redi",
    "provider",
    "rvm_",
    "rvm-",
    "rvm.",
    "program",
    "memcached",
    "rail",
    "silex",
    "foreman",
    "activity",
    "license",
    "strategy",
    "batch",
    "streaming",
    "fast",
    "use_",
    "use-",
    "use.",
    "usb_",
    "usb-",
    "usb.",
    "impres",
    "academy",
    "slider",
    "please",
    "layer",
    "cros",
    "now_",
    "now-",
    "now.",
    "miner",
    "extension",
    "own_",
    "own-",
    "own.",
    "app_",
    "app-",
    "app.",
    "debian",
    "symphony",
    "example",
    "feature",
    "serie",
    "tree",
    "project",
    "runner",
    "entry",
    "leetcode",
    "layout",
    "webrtc",
    "logic",
    "login",
    "worker",
    "toolkit",
    "mocha",
    "support",
    "back",
    "inside",
    "device",
    "jenkin",
    "contact",
    "fake",
    "awesome",
    "ocaml",
    "bit_",
    "bit-",
    "bit.",
    "drive",
    "screen",
    "prototype",
    "gist",
    "binary",
    "nosql",
    "rest",
    "overview",
    "dart",
    "dark",
    "emac",
    "mongoid",
    "solarized",
    "homepage",
    "emulator",
    "commander",
    "django",
    "yandex",
    "gradle",
    "xcode",
    "writer",
    "crm_",
    "crm-",
    "crm.",
    "jade",
    "startup",
    "error",
    "using",
    "format",
    "name",
    "spring",
    "parser",
    "scratch",
    "magic",
    "try_",
    "try-",
    "try.",
    "rack",
    "directive",
    "challenge",
    "slim",
    "counter",
    "element",
    "chosen",
    "doc_",
    "doc-",
    "doc.",
    "meta",
    "should",
    "button",
    "packet",
    "stream",
    "hardware",
    "android",
    "infinite",
    "password",
    "software",
    "ghost",
    "xamarin",
    "spec",
    "chef",
    "interview",
    "hubot",
    "mvc_",
    "mvc-",
    "mvc.",
    "exercise",
    "leaflet",
    "launcher",
    "air_",
    "air-",
    "air.",
    "photo",
    "board",
    "boxen",
    "way_",
    "way-",
    "way.",
    "computing",
    "welcome",
    "notepad",
    "portfolio",
    "cat_",
    "cat-",
    "cat.",
    "can_",
    "can-",
    "can.",
    "magento",
    "yaml",
    "domain",
    "card",
    "yii_",
    "yii-",
    "yii.",
    "checker",
    "browser",
    "upgrade",
    "only",
    "progres",
    "aura",
    "ruby_",
    "ruby-",
    "ruby.",
    "polymer",
    "util",
    "lite",
    "hackathon",
    "rule",
    "log_",
    "log-",
    "log.",
    "opengl",
    "stanford",
    "skeleton",
    "history",
    "inspector",
    "help",
    "soon",
    "selenium",
    "lab_",
    "lab-",
    "lab.",
    "scheme",
    "schema",
    "look",
    "ready",
    "leveldb",
    "docker",
    "game",
    "minimal",
    "logstash",
    "messaging",
    "within",
    "heroku",
    "mongodb",
    "kata",
    "suite",
    "picker",
    "win_",
    "win-",
    "win.",
    "wip_",
    "wip-",
    "wip.",
    "panel",
    "started",
    "starter",
    "front-end",
    "detector",
    "deploy",
    "editing",
    "based",
    "admin",
    "capture",
    "spree",
    "page",
    "bundle",
    "goal",
    "rpg_",
    "rpg-",
    "rpg.",
    "setup",
    "side",
    "mean",
    "reader",
    "cookbook",
    "mini",
    "modern",
    "seed",
    "dom_",
    "dom-",
    "dom.",
    "doc_",
    "doc-",
    "doc.",
    "dot_",
    "dot-",
    "dot.",
    "syntax",
    "sugar",
    "loader",
    "website",
    "make",
    "kit_",
    "kit-",
    "kit.",
    "protocol",
    "human",
    "daemon",
    "golang",
    "manager",
    "countdown",
    "connector",
    "swagger",
    "map_",
    "map-",
    "map.",
    "mac_",
    "mac-",
    "mac.",
    "man_",
    "man-",
    "man.",
    "orm_",
    "orm-",
    "orm.",
    "org_",
    "org-",
    "org.",
    "little",
    "zsh_",
    "zsh-",
    "zsh.",
    "shop",
    "show",
    "workshop",
    "money",
    "grid",
    "server",
    "octopres",
    "svn_",
    "svn-",
    "svn.",
    "ember",
    "embed",
    "general",
    "file",
    "important",
    "dropbox",
    "portable",
    "public",
    "docpad",
    "fish",
    "sbt_",
    "sbt-",
    "sbt.",
    "done",
    "para",
    "network",
    "common",
    "readme",
    "popup",
    "simple",
    "purpose",
    "mirror",
    "single",
    "cordova",
    "exchange",
    "object",
    "design",
    "gateway",
    "account",
    "lamp",
    "intellij",
    "math",
    "mit_",
    "mit-",
    "mit.",
    "control",
    "enhanced",
    "emitter",
    "multi",
    "add_",
    "add-",
    "add.",
    "about",
    "socket",
    "preview",
    "vagrant",
    "cli_",
    "cli-",
    "cli.",
    "powerful",
    "top_",
    "top-",
    "top.",
    "radio",
    "watch",
    "fluid",
    "amazon",
    "report",
    "couchbase",
    "automatic",
    "detection",
    "sprite",
    "pyramid",
    "portal",
    "advanced",
    "plu_",
    "plu-",
    "plu.",
    "runtime",
    "git_",
    "git-",
    "git.",
    "uri_",
    "uri-",
    "uri.",
    "haml",
    "node",
    "sql_",
    "sql-",
    "sql.",
    "cool",
    "core",
    "obsolete",
    "handler",
    "iphone",
    "extractor",
    "array",
    "copy",
    "nlp_",
    "nlp-",
    "nlp.",
    "reveal",
    "pop_",
    "pop-",
    "pop.",
    "engine",
    "parse",
    "check",
    "html",
    "nest",
    "all_",
    "all-",
    "all.",
    "chinese",
    "buildpack",
    "what",
    "tag_",
    "tag-",
    "tag.",
    "proxy",
    "style",
    "cookie",
    "feed",
    "restful",
    "compiler",
    "creating",
    "prelude",
    "context",
    "java",
    "rspec",
    "mock",
    "backbone",
    "light",
    "spotify",
    "flex",
    "related",
    "shell",
    "which",
    "clas",
    "webapp",
    "swift",
    "ansible",
    "unity",
    "console",
    "tumblr",
    "export",
    "campfire",
    "conway'",
    "made",
    "riak",
    "hero",
    "here",
    "unix",
    "unit",
    "glas",
    "smtp",
    "how_",
    "how-",
    "how.",
    "hot_",
    "hot-",
    "hot.",
    "debug",
    "release",
    "diff",
    "player",
    "easy",
    "right",
    "old_",
    "old-",
    "old.",
    "animate",
    "time",
    "push",
    "explorer",
    "course",
    "training",
    "nette",
    "router",
    "draft",
    "structure",
    "note",
    "salt",
    "where",
    "spark",
    "trello",
    "power",
    "method",
    "social",
    "via_",
    "via-",
    "via.",
    "vim_",
    "vim-",
    "vim.",
    "select",
    "webkit",
    "github",
    "ftp_",
    "ftp-",
    "ftp.",
    "creator",
    "mongoose",
    "led_",
    "led-",
    "led.",
    "movie",
    "currently",
    "pdf_",
    "pdf-",
    "pdf.",
    "load",
    "markdown",
    "phalcon",
    "input",
    "custom",
    "atom",
    "oracle",
    "phonegap",
    "ubuntu",
    "great",
    "rdf_",
    "rdf-",
    "rdf.",
    "popcorn",
    "firefox",
    "zip_",
    "zip-",
    "zip.",
    "cuda",
    "dotfile",
    "static",
    "openwrt",
    "viewer",
    "powered",
    "graphic",
    "les_",
    "les-",
    "les.",
    "doe_",
    "doe-",
    "doe.",
    "maven",
    "word",
    "eclipse",
    "lab_",
    "lab-",
    "lab.",
    "hacking",
    "steam",
    "analytic",
    "option",
    "abstract",
    "archive",
    "reality",
    "switcher",
    "club",
    "write",
    "kafka",
    "arduino",
    "angular",
    "online",
    "title",
    "don't",
    "contao",
    "notice",
    "analyzer",
    "learning",
    "zend",
    "external",
    "staging",
    "busines",
    "tdd_",
    "tdd-",
    "tdd.",
    "scanner",
    "building",
    "snippet",
    "modular",
    "bower",
    "stm_",
    "stm-",
    "stm.",
    "lib_",
    "lib-",
    "lib.",
    "alpha",
    "mobile",
    "clean",
    "linux",
    "nginx",
    "manifest",
    "some",
    "raspberry",
    "gnome",
    "ide_",
    "ide-",
    "ide.",
    "block",
    "statistic",
    "info",
    "drag",
    "youtube",
    "koan",
    "facebook",
    "paperclip",
    "art_",
    "art-",
    "art.",
    "quality",
    "tab_",
    "tab-",
    "tab.",
    "need",
    "dojo",
    "shield",
    "computer",
    "stat",
    "state",
    "twitter",
    "utility",
    "converter",
    "hosting",
    "devise",
    "liferay",
    "updated",
    "force",
    "tip_",
    "tip-",
    "tip.",
    "behavior",
    "active",
    "call",
    "answer",
    "deck",
    "better",
    "principle",
    "ches",
    "bar_",
    "bar-",
    "bar.",
    "reddit",
    "three",
    "haxe",
    "just",
    "plug-in",
    "agile",
    "manual",
    "tetri",
    "super",
    "beta",
    "parsing",
    "doctrine",
    "minecraft",
    "useful",
    "perl",
    "sharing",
    "agent",
    "switch",
    "view",
    "dash",
    "channel",
    "repo",
    "pebble",
    "profiler",
    "warning",
    "cluster",
    "running",
    "markup",
    "evented",
    "mod_",
    "mod-",
    "mod.",
    "share",
    "csv_",
    "csv-",
    "csv.",
    "response",
    "good",
    "house",
    "connect",
    "built",
    "build",
    "find",
    "ipython",
    "webgl",
    "big_",
    "big-",
    "big.",
    "google",
    "scala",
    "sdl_",
    "sdl-",
    "sdl.",
    "sdk_",
    "sdk-",
    "sdk.",
    "native",
    "day_",
    "day-",
    "day.",
    "puppet",
    "text",
    "routing",
    "helper",
    "linkedin",
    "crawler",
    "host",
    "guard",
    "merchant",
    "poker",
    "over",
    "writing",
    "free",
    "classe",
    "component",
    "craft",
    "nodej",
    "phoenix",
    "longer",
    "quick",
    "lazy",
    "memory",
    "clone",
    "hacker",
    "middleman",
    "factory",
    "motion",
    "multiple",
    "tornado",
    "hack",
    "ssh_",
    "ssh-",
    "ssh.",
    "review",
    "vimrc",
    "driver",
    "driven",
    "blog",
    "particle",
    "table",
    "intro",
    "importer",
    "thrift",
    "xmpp",
    "framework",
    "refresh",
    "react",
    "font",
    "librarie",
    "variou",
    "formatter",
    "analysi",
    "karma",
    "scroll",
    "tut_",
    "tut-",
    "tut.",
    "apple",
    "tag_",
    "tag-",
    "tag.",
    "tab_",
    "tab-",
    "tab.",
    "category",
    "ionic",
    "cache",
    "homebrew",
    "reverse",
    "english",
    "getting",
    "shipping",
    "clojure",
    "boot",
    "book",
    "branch",
    "combination",
    "combo",
]



for stopword in stopwords:
  pass
  print(stopword)



